import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

import { ConvexClientProvider } from './ConvexClientProvider';
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            <ConvexClientProvider>{children}</ConvexClientProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
